const englishText = {
  BUDGET: "Budget",
  SPENT: "Spent",
  REMAINING: "Remaining",
  SPENT_DATE: "spent date",
  AMOUNT: "amount",
  NO_PAYMENT_DATA: "No Payment Data",
  YEN: "yen",
  SEND: "send",
  RESEND: "resend",
  SENT_RESET_LINK: "We have sent you a reset link.",
  RESEND_RESET_LINK: "resend reset link",
  RESET: "reset",
  ADD: "add",
  CHANGE: "change",
  DELETE: "delete",
  FIX_AMOUNT: "fix amount",
  ENTER_AMOUNT: "enter amount",
  CREATE_ACCOUNT: "Create account",
  ALREADY_HAVE_AN_ACCOUNT: "Already have an account?",
  PASSWORD: "Password",
  START_BUDGETING: "Start Budgeting",
  CHANGE_PASSWORD: "change password",
  CURRENT_PASSWORD: "Current Password",
  NEW_PASSWORD: "New Password",
  REENTER_PASSWORD: "Reenter password",
  REENTER_NEW_PASSWORD: "Reenter New Password",
  ENTER_PASSWORD: "Enter password",
  PASSWORD_CONDITION_01: "only alphanumeric characters",
  PASSWORD_CONDITION_02: "use 6 to 20 characters",
  NOT_CORRECT_PASSWORD: "Not correct password",
  FORGET_PASSWORD: "Forget password?",
  PASSWORD_CHANGED: "password changed",
  ENTER_YOUR_EMAIL_ADDRESS: "Enter your email address.",
  PASSWORD_PLACEHOLDER: "e.g. password0000",
  RESET_PASSWORD: "Reset password",
  MAIL_ADDRESS: "Mail address",
  MAIL_ADDRESS_PLACEHOLDER: "e.g. mail@example.com",
  SIGN_IN: "Sign In",
  SIGN_OUT: "Sign Out",
  SIGN_UP: "Sign Up",
  LP_TEXT_01: "simplify monthly budgeting",
  LP_TEXT_02: "Are you managing your monthly budget effectively?",
  LP_TEXT_03:
    "Credit card statements take time to reflect, and it's difficult to determine how much you have spent since the beginning of the month.",
  LP_TEXT_04:
    "With the budget management tool 'Pay History,' you can easily manage your monthly budget, track your spending, and monitor your budget balance.",
  HOW_TO_USE: "How To Use",
  HOW_TO_USE_01: "Enter monthly budget.",
  HOW_TO_USE_02: "When you make a payment, enter the amount in this app.",
  HOW_TO_USE_03: "Complete!",
  NOT_FOUND_TEXT: "We're Sorry, The page you requested could not be found.",
  ACCOUNT_NOT_FOUND: "Account not found",
  EMAIL_ALREADY_IN_USE:
    "The provided email is already in use by an existing user. Each user must have a unique email.",
  UNKNOWN_ERROR: "Unknown error",
};

export default englishText;
