const japaneseText = {
  BUDGET: "予算",
  SPENT: "支出",
  REMAINING: "残高",
  SPENT_DATE: "支出日",
  AMOUNT: "金額",
  NO_PAYMENT_DATA: "支払いデータがありません。",
  YEN: "円",
  SEND: "送信",
  RESEND: "再送信",
  SENT_RESET_LINK: "We have sent you a reset link.",
  RESEND_RESET_LINK: "再設定リンクをもう一度送信",
  RESET: "再設定",
  ADD: "追加",
  CHANGE: "変更",
  DELETE: "削除",
  FIX_AMOUNT: "支払データ修正",
  ENTER_AMOUNT: "支出額を入力",
  CREATE_ACCOUNT: "アカウント作成",
  ALREADY_HAVE_AN_ACCOUNT: "アカウントをお持ちの場合はこちら",
  PASSWORD: "パスワード",
  CHANGE_PASSWORD: "パスワード変更",
  CURRENT_PASSWORD: "現在のパスワード",
  NEW_PASSWORD: "新しいパスワード",
  REENTER_PASSWORD: "パスワードを再入力",
  REENTER_NEW_PASSWORD: "新しいパスワードを再入力",
  ENTER_PASSWORD: "パスワードを入力してください。",
  START_BUDGETING: "予算管理を始める",
  PASSWORD_CONDITION_01: "半角英数字のみ使用できます。",
  PASSWORD_CONDITION_02: "6から20文字で入力してください。",
  NOT_CORRECT_PASSWORD: "パスワードが一致しませんでした。",
  FORGET_PASSWORD: "パスワードをお忘れの場合はこちら",
  PASSWORD_CHANGED: "パスワードを変更しました。",
  WRONG_PASSWORD: "パスワードが間違っています。",
  TOO_MANY_REQUESTS:
    "所定の回数以上パスワードを間違えました。時間をおいてお試しください。",
  ENTER_YOUR_EMAIL_ADDRESS: "メールアドレスを入力してください。",
  EMAIL_ALREADY_USE: "このメールアドレスは既に使用されています。",
  WEAK_PASSWORD: "パスワードが脆弱です。6文字以上で入力してください。",
  PROVIDER_ALREADY_LINKED: "既にサインイン済みです。",
  INVALID_ACTION_CODE: "無効な再設定リンクです。",
  EXPIRED_ACTION_CODE: "再設定リンクの有効期限が切れています。",
  PASSWORD_PLACEHOLDER: "例) password0000",
  RESET_PASSWORD: "パスワード再設定",
  MAIL_ADDRESS: "メールアドレス",
  MAIL_ADDRESS_PLACEHOLDER: "例) mail@example.com",
  SIGN_IN: "サインイン",
  SIGN_OUT: "サインアウト",
  SIGN_UP: "サインアップ",
  LP_TEXT_01: "毎月の予算管理をシンプルに",
  LP_TEXT_02: "月の予算管理、しっかりできていますか？",
  LP_TEXT_03:
    "クレジットカード明細は反映まで時間がかかってしまい、月初からいくら使ったのか把握するのは難しいですよね。",
  LP_TEXT_04:
    "予算管理ツール「PayHistory」なら、月の予算、支出額、予算の残高を最もシンプルに管理できます。",
  HOW_TO_USE: "使い方",
  HOW_TO_USE_01: "月の予算を入力する",
  HOW_TO_USE_02: "支払いしたらアプリで金額を入力",
  HOW_TO_USE_03: "完了!",
  NOT_FOUND_TEXT: "申し訳ございません。お探しのページは見つかりませんでした。",
  ACCOUNT_NOT_FOUND: "アカウントが見つかりませんでした。",
  UNKNOWN_ERROR: "不明なエラーが発生しました。",
  USER_DISABLED: "アカウントが無効になっています。",
  INVALID_EMAIL: "メールアドレス形式が正しくありません。",
  EMAIL_ALREADY_IN_USE: "email-already-in-use",
};

export default japaneseText;
