name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create .env.local
        run: |
          touch .env.local
          echo NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }} >> .env.local
          echo NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} >> .env.local
          echo NEXT_PUBLIC_FIREBASE_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_DOMAIN }} >> .env.local
          echo NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} >> .env.local
          echo NEXT_PUBLIC_FIREBASE_STORAGE=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE }} >> .env.local
          echo NEXT_PUBLIC_FIREBASE_MESSAGING_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_ID }} >> .env.local
          echo NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }} >> .env.local
          echo NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }} >> .env.local

      - name: Run ESLint
        run: pnpm lint

      - name: Run Jest
        run: pnpm test

      - name: Build Next.js app
        run: pnpm build

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          start: pnpm start
          wait-on: "http://localhost:3000"
