name: Jest and ESLint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
      - name: Install dependencies
        run: pnpm install
      - name: Run Jest
        run: pnpm test -- --coverage
      - name: Run ESLint
        run: pnpm lint
      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
