name: jest

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
      - name: Install dependencies
        working-directory: /home/runner/work/pay-history/pay-history
        run: pnpm install
      - name: Run Jest
        working-directory: /home/runner/work/pay-history/pay-history
        run: pnpm test
      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
